export const LLM = {
  MODEL: 'gpt-4o-mini',
  MAX_TOKENS: 512,
  TEMPERATURE: 0.4,
  HISTORY_WINDOW: 20,
} as const;

export const RAG = {
  TOP_K: 3,
} as const;

export const LIMITS = {
  MSG_MAX_LEN: 2000,
  CUSTOMER_ID_MAX_LEN: 50,
  CUSTOMER_NAME_MAX_LEN: 100,
  RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
  RATE_LIMIT_MAX: 100,
  JSON_BODY: '50kb',
} as const;

export const CONTEXT_TAGS = {
  ACTIVE_CUSTOMER: 'ACTIVE_CUSTOMER',
  IDENTITY_CONFLICT: 'IDENTITY_CONFLICT',
  ORDERS_FOR_CUSTOMER: 'ORDERS_FOR_CUSTOMER',
  NO_ACTIVE_CUSTOMER: 'NO_ACTIVE_CUSTOMER',
  MY_ORDERS_FOUND: 'MY_ORDERS_FOUND',
  MY_ORDERS_NONE: 'MY_ORDERS_NONE',
  MY_ORDERS_ERROR: 'MY_ORDERS_ERROR',
  ORDER_FOUND: 'ORDER_FOUND',
  NO_ORDER_FOUND: 'NO_ORDER_FOUND',
  NO_ORDERS_FOUND: 'NO_ORDERS_FOUND',
  MULTIPLE_ORDERS_FOUND: 'MULTIPLE_ORDERS_FOUND',
  ORDER_BELONGS_TO_OTHER: 'ORDER_BELONGS_TO_OTHER',
} as const;
